export default {
  GET_PROFILE: 'GET_PROFILE',

  GET_HEROES_COMPETITION: 'GET_HEROES_COMPETITION',
  GET_HEROES_QUICK: 'GET_HEROES_QUICK',

  GET_HEROES_COMPETITION: 'GET_HEROES_COMPETITION',
  GET_HEROES_QUICK: 'GET_HEROES_QUICK',

  GET_ALL_HEROES_COMPETITION: 'GET_ALL_HEROESCOMPETITION',
  GET_ALL_HEROES_QUICK: 'GET_ALL_HEROES_QUICK',
};